version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - cache_data:/app/cache
      - vector_store_data:/app/chroma_db
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - TZ=Europe/Istanbul
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - ragollama_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ragollama_network

networks:
  ragollama_network:
    driver: bridge

volumes:
  ollama_data:
  cache_data:
  vector_store_data: 