version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
      - cache_data:/app/cache
      - vector_store_data:/app/chroma_db
    environment:
      - OLLAMA_HOST=http://ollama:11435
      - TZ=Europe/Istanbul
      - CUDA_VISIBLE_DEVICES=0,1
    restart: unless-stopped
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    networks:
      - ragollama_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11435"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - CUDA_VISIBLE_DEVICES=0,1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OLLAMA_HOST=0.0.0.0:11435
      - OLLAMA_MODELS=/root/.ollama
      - OLLAMA_NUM_GPU_LAYERS=9999
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_BATCH_SIZE=8192
      - OLLAMA_GPUMEMORY=96000MB
      - OLLAMA_GPUSPLIT="48,48"
      - OLLAMA_CONTEXT_LENGTH=131072
      - GGML_CUDA_ENABLE_UNIFIED_MEMORY=1
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_DEBUG=1
      - OLLAMA_ACCELERATE=1
      - OLLAMA_NOPRUNE=1
      - OLLAMA_MAX_LOADED_MODELS=5
      - OLLAMA_LOAD_TIMEOUT=0
      - OLLAMA_NOHISTORY=0
      - gpus=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ragollama_network

networks:
  ragollama_network:
    driver: bridge

volumes:
  ollama_data:
  cache_data:
  vector_store_data: 